language: ruby
cache: bundler
bundler_args: --without documentation production
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - rbx
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: f2de698e1077758563b8f651f1c5aee9938816f589e6f8a0b63e320676d4bd69
